# Generated by Django 3.1.7 on 2021-05-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.URLField(blank=True, default='blank')),
                ('descript', models.CharField(max_length=128)),
                ('price', models.FloatField(blank=0.0, default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=32)),
                ('categoryimage', models.URLField(blank=True, default='blank')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentarea', models.CharField(blank='', default='', max_length=256)),
                ('auction', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='auctioncomment', to='auctions.auctionlisting')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(blank=0.0, default=1.0)),
                ('auction', models.ForeignKey(default=1.1, on_delete=django.db.models.deletion.CASCADE, related_name='auctionbid', to='auctions.auctionlisting')),
            ],
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctioncategory', to='auctions.category'),
        ),
    ]
