# Generated by Django 3.1.7 on 2021-05-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='usercomment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to='auctions.user'),
            preserve_default=False,
        ),
    ]
