# Generated by Django 3.1.7 on 2021-05-10 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlisting',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='usercomment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceonmoment', models.FloatField()),
                ('auctions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userwishes',
            field=models.ManyToManyField(through='auctions.UserWishlist', to='auctions.AuctionListing'),
        ),
    ]
