# Generated by Django 3.1.7 on 2021-05-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210510_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userwishes',
            field=models.ManyToManyField(default=None, through='auctions.UserWishlist', to='auctions.AuctionListing'),
        ),
    ]
