# Generated by Django 3.1.7 on 2021-05-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210511_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='userauction',
            field=models.CharField(default='', max_length=64),
        ),
    ]
