# Generated by Django 3.1.7 on 2021-05-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_userauction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='userauction',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
