# Generated by Django 3.1.7 on 2021-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210511_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='userauction',
            field=models.CharField(max_length=64),
        ),
    ]
