# Generated by Django 3.1.7 on 2021-05-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210511_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionFinished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('descript', models.CharField(max_length=128)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=64)),
                ('price', models.FloatField(blank=0.0, default=1.0)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('userauction', models.CharField(max_length=64)),
            ],
        ),
    ]
