# Generated by Django 3.1.7 on 2021-05-12 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionfinished',
            name='datefinished',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionfinished',
            name='winner',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionfinished',
            name='datecreate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.FloatField(blank=0.0),
        ),
    ]
