# Generated by Django 3.1.7 on 2021-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210512_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='openess',
            field=models.BooleanField(default=True),
        ),
    ]
